In [1]:
import pandas as pd

In [17]:
data = {
    'date': ['2021-12-01', '01-12-2022', '2022/12/01', '12-01-2021'],
    'country': ['USA', 'U.S.A.', 'America', 'United States'],
    'name': ['Aammar', 'Amaar', 'Hamza', 'Hazma'],
    'sales_2020': [100, 200, None, 200],
    'sales_2021': [None, 150, 300, 150]
}
# make pandas dataframe
df = pd.DataFrame(data)

In [18]:
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01            USA  Aammar       100.0         NaN
1  01-12-2022         U.S.A.   Amaar       200.0       150.0
2  2022/12/01        America   Hamza         NaN       300.0
3  12-01-2021  United States   Hazma       200.0       150.0

In [25]:
# strandardizing the date format
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['date'] = df['date'].dt.strftime('%Y-%m-%d')
df.head()

         date  country    name  sales_2020  sales_2021
0  2021-12-01      USA  Aammar       100.0         NaN
2         NaN  America   Hamza         NaN       300.0

# impute fill the date and try another method to complete the data format inconsistencies

In [26]:
# impute fill the date
df['date'] = df['date'].ffill()
df.head()

         date  country    name  sales_2020  sales_2021
0  2021-12-01      USA  Aammar       100.0         NaN
2  2021-12-01  America   Hamza         NaN       300.0

In [10]:
# harmonizing names of countries 
df['country'] = df['country'].replace({
    'U.S.A.': 'United States',
    'America': 'United States',
    'USA': 'United States'
})
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01  United States  Aammar       100.0         NaN
1         NaN  United States   Amaar       200.0       150.0
2         NaN  United States   Hamza         NaN       300.0
3         NaN  United States   Hazma       200.0       150.0

In [14]:
# Correct the typographical mistakes in name '
df['name'] = df['name'].replace({
    'Amaar': 'Aammar',
    'Hazma': 'Hamza'
})
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01  United States  Aammar       100.0         NaN
1         NaN  United States  Aammar       200.0       150.0
2         NaN  United States   Hamza         NaN       300.0
3         NaN  United States   Hamza       200.0       150.0

In [16]:
# remove the duplicates
df = df.drop_duplicates(subset=['name'])
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01  United States  Aammar       100.0         NaN
2         NaN  United States   Hamza         NaN       300.0

In [19]:
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01            USA  Aammar       100.0         NaN
1  01-12-2022         U.S.A.   Amaar       200.0       150.0
2  2022/12/01        America   Hamza         NaN       300.0
3  12-01-2021  United States   Hazma       200.0       150.0

In [21]:
# resolving contradictory data
# For demonstration, let's assume sales_2021 should always be heigher than sales_2020
# we'll remove rows where this condition is not met
df = df.drop(df[df['sales_2021'] <= df['sales_2020']].index)
df.head()

         date  country    name  sales_2020  sales_2021
0  2021-12-01      USA  Aammar       100.0         NaN
2  2022/12/01  America   Hamza         NaN       300.0