# inverce encoding / inverse transform /decoding categorical variables

inverse encoding is the process of transforming numeric features into categorical features and vice versa. this method is available for the following methods:

- label encoding
- one hot encoding
- ordinal encoding

In [21]:
# import laibraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split   
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [27]:
# load the data 
df = sns.load_dataset('titanic')
df.head()

   survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [28]:
import warnings
warnings.filterwarnings('ignore')

# impute the missing values from age, embarked, embark_town and  drop the deck column
df['age'].fillna(df['age'].mean(), inplace=True)
df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)
df['embark_town'].fillna(df['embark_town'].mode()[0], inplace=True)
# drop the deck column 
df.drop('deck', axis=1, inplace=True)

import warnings
warnings.filterwarnings('ignore')

In [25]:
le_sex = LabelEncoder()
le_embarked = LabelEncoder()
le_embark_town = LabelEncoder()
le_alive = LabelEncoder()
le_alone = LabelEncoder()
le_who = LabelEncoder()
le_class = LabelEncoder()

df['sex'] = le_sex.fit_transform(df['sex'])
df['embarked'] = le_embarked.fit_transform(df['embarked'])
df['embark_town'] = le_embark_town.fit_transform(df['embark_town'])
df['alive'] = le_alive.fit_transform(df['alive'])
df['alone'] = le_alone.fit_transform(df['alone'])
df['who'] = le_who.fit_transform(df['who'])
df['class'] = le_class.fit_transform(df['class'])
df.head()

   survived  pclass  sex   age  ...  adult_male  embark_town  alive  alone
0         0       3    1  22.0  ...        True            2      0      0
1         1       1    0  38.0  ...       False            0      1      0
2         1       3    0  26.0  ...       False            2      1      1
3         1       1    0  35.0  ...       False            2      1      0
4         0       3    1  35.0  ...        True            2      0      1

[5 rows x 14 columns]

In [26]:
# inverse transform the data 
df['sex'] = le_sex.inverse_transform(df['sex'])
df.head()

   survived  pclass     sex   age  ...  adult_male  embark_town  alive  alone
0         0       3    male  22.0  ...        True            2      0      0
1         1       1  female  38.0  ...       False            0      1      0
2         1       3  female  26.0  ...       False            2      1      1
3         1       1  female  35.0  ...       False            2      1      0
4         0       3    male  35.0  ...        True            2      0      1

[5 rows x 14 columns]

In [ ]:
oe_sex = OrdinalEncoder()
oe_embarked = OrdinalEncoder()
oe_embark_town = OrdinalEncoder()
oe_alive = OrdinalEncoder()
oe_alone = OrdinalEncoder()
oe_who = OrdinalEncoder()
oe_class = OrdinalEncoder()

df['sex'] = oe_sex.fit_transform(df[['sex']])
df['embarked'] = oe_embarked.fit_transform(df[['embarked']])
df['embark_town'] = oe_embark_town.fit_transform(df[['embark_town']])    
df['alive'] = oe_alive.fit_transform(df[['alive']])
df['alone'] = oe_alone.fit_transform(df[['alone']])
df['who'] = oe_who.fit_transform(df[['who']])
df['class'] = oe_class.fit_transform(df[['class']])
df.head()

   survived  pclass  sex   age  ...  adult_male  embark_town  alive  alone
0         0       3  1.0  22.0  ...        True          2.0    0.0    0.0
1         1       1  0.0  38.0  ...       False          0.0    1.0    0.0
2         1       3  0.0  26.0  ...       False          2.0    1.0    1.0
3         1       1  0.0  35.0  ...       False          2.0    1.0    0.0
4         0       3  1.0  35.0  ...        True          2.0    0.0    1.0

[5 rows x 14 columns]

In [32]:
# Add .ravel() to flatten the result
df['sex'] = oe_sex.inverse_transform(df[['sex']]).ravel()
df.head()

   survived  pclass     sex   age  ...  adult_male  embark_town  alive  alone
0         0       3    male  22.0  ...        True          2.0    0.0    0.0
1         1       1  female  38.0  ...       False          0.0    1.0    0.0
2         1       3  female  26.0  ...       False          2.0    1.0    1.0
3         1       1  female  35.0  ...       False          2.0    1.0    0.0
4         0       3    male  35.0  ...        True          2.0    0.0    1.0

[5 rows x 14 columns]

# one hot encoding

In [74]:
from sklearn.preprocessing import OneHotEncoder

df = sns.load_dataset('titanic')

cat_columns = ['sex', 'embarked']

encoder = OneHotEncoder(sparse_output=False)
encoded_df = pd.DataFrame(encoder.fit_transform(df[cat_columns]))

# concatenate the dataframes
df = pd.concat([df, encoded_df], axis=1)
# df.drop(cat_columns, axis=1, inplace=True)
df.head()

   survived  pclass     sex   age  sibsp  parch  ...    0    1    2    3    4    5
0         0       3    male  22.0      1      0  ...  0.0  1.0  0.0  0.0  1.0  0.0
1         1       1  female  38.0      1      0  ...  1.0  0.0  1.0  0.0  0.0  0.0
2         1       3  female  26.0      0      0  ...  1.0  0.0  0.0  0.0  1.0  0.0
3         1       1  female  35.0      1      0  ...  1.0  0.0  0.0  0.0  1.0  0.0
4         0       3    male  35.0      0      0  ...  0.0  1.0  0.0  0.0  1.0  0.0

[5 rows x 21 columns]

In [75]:
# we need to extract the orignal categories for each encoded column
original_categories = {col: encoder.categories_[i] for i, col in enumerate(cat_columns)}

# Manual creation of feature names
feature_names = []
for i, col in enumerate(cat_columns):
    for category in encoder.categories_[i]:
        feature_names.append(f"{col}_{category}")

encoded_df = pd.DataFrame(encoded_df, columns=feature_names)

In [76]:
df.head()

   survived  pclass     sex   age  sibsp  parch  ...    0    1    2    3    4    5
0         0       3    male  22.0      1      0  ...  0.0  1.0  0.0  0.0  1.0  0.0
1         1       1  female  38.0      1      0  ...  1.0  0.0  1.0  0.0  0.0  0.0
2         1       3  female  26.0      0      0  ...  1.0  0.0  0.0  0.0  1.0  0.0
3         1       1  female  35.0      1      0  ...  1.0  0.0  0.0  0.0  1.0  0.0
4         0       3    male  35.0      0      0  ...  0.0  1.0  0.0  0.0  1.0  0.0

[5 rows x 21 columns]